PROG =		kc

DESTDIR ?=	
PREFIX ?=	usr/local

SRCS =		kc.c malloc_check.c
SRCS +=		cmd_c.c cmd_cdel.c cmd_clear.c cmd_clist.c cmd_cnew.c cmd_copy.c \
		cmd_cren.c cmd_del.c cmd_edit.c cmd_export.c cmd_getnum.c \
		cmd_help.c cmd_import.c cmd_info.c cmd_list.c cmd_new.c cmd_passwd.c \
		cmd_quit.c cmd_random.c cmd_search.c cmd_searchre.c cmd_status.c \
		cmd_version.c cmd_write.c \
		commands.c commands_init.c
OBJS =		kc.o malloc_check.o
OBJS +=		cmd_c.o cmd_cdel.o cmd_clear.o cmd_clist.o cmd_cnew.o cmd_copy.o \
		cmd_cren.o cmd_del.o cmd_edit.o cmd_export.o cmd_getnum.o \
		cmd_help.o cmd_import.o cmd_info.o cmd_list.o cmd_new.o cmd_passwd.o \
		cmd_quit.o cmd_random.o cmd_search.o cmd_searchre.o cmd_status.o \
		cmd_version.o cmd_write.o \
		commands.o commands_init.o

CFLAGS +=	-pedantic -Wall -g
CFLAGS +=	`pkg-config --cflags libssl`
CFLAGS +=	`pkg-config --cflags libbsd`
CFLAGS +=	`pkg-config --cflags libxml-2.0`
CFLAGS +=	-D_LINUX
ifndef EDITLINE
CFLAGS +=	-D_READLINE
endif
ifdef HAVE_PCRE
CFLAGS +=	`pkg-config --cflags libpcre` -D_HAVE_PCRE
endif

LDADD +=	`pkg-config --libs libssl`
LDADD +=	`pkg-config --libs libbsd`
LDADD +=	`pkg-config --libs libxml-2.0`
ifdef EDITLINE
LDADD +=	-ledit -lncursesw
else
LDADD +=	-lreadline -ltermcap
endif
ifdef HAVE_PCRE
LDADD +=	`pkg-config --libs libpcre`
endif


all: ${PROG}

clean:
	rm -f *.o kc regress/test*

install:
	install -D -s -o root -m 755 kc ${DESTDIR}/${PREFIX}/bin/kc
	install -D -o root -m 644 kc.1 ${DESTDIR}/${PREFIX}/man/man1/kc.1

test:
	sh regress/run_tests.sh

${PROG}: ${OBJS}
	${CC} -o ${PROG} ${CFLAGS} ${LDADD} \
		${SRCS}
