.\"Copyright (c) 2011, 2012 LEVAI Daniel
.\"All rights reserved.
.\"Redistribution and use in source and binary forms, with or without
.\"modification, are permitted provided that the following conditions are met:
.\"	* Redistributions of source code must retain the above copyright
.\"	notice, this list of conditions and the following disclaimer.
.\"	* Redistributions in binary form must reproduce the above copyright
.\"	notice, this list of conditions and the following disclaimer in the
.\"	documentation and/or other materials provided with the distribution.
.\"THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
.\"ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
.\"WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
.\"DISCLAIMED. IN NO EVENT SHALL LEVAI Daniel BE LIABLE FOR ANY
.\"DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
.\"(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
.\"LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
.\"ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\"(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
.\"SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.Dd Dec 28, 2012
.Dt KC 1
.Os
.Sh NAME
.Nm kc
.Nd console based username and password management application
.Sh SYNOPSIS
.Nm kc
.Op Fl k Ar database file
.Op Fl r
.Op Fl p Ar password file
.Op Fl m Ar cipher mode
.Op Fl b
.Op Fl v
.Op Fl h
.Sh DESCRIPTION
The
.Nm
utility is a console based username and password management application using an encrypted XML document as its database.
.Pp
A database file can contain multiple keychains, and keychains in turn can contain multiple keys (usernames if you like) and values (passwords if you like).
.Pp
After starting
.Nm
the
.Cm help
command shows the available commands, and usage information for them.
.Pp
The CLI supports tab-completion for commands and keychains.
.Pp
There is a utility in the source package that can convert an exported pwsafe database to a
.Nm
compatible XML database, which can be imported using the
.Cm import
command.
.Pp
.Em NOTE :
Currently there is no character set conversion taking place in the program. You either input UTF-8 and be ready to display it, or you don't input anything other than US-ASCII. You would still be able to read the database after not UTF-8 nor US-ASCII (eg.: latin2) input, but not in the way you would expect it. You can "repair" such databases, by exporting (see the
.Cm xport
command below), converting the plain text XML file to UTF-8, then importing the database. (see the
.Cm import
command below).
.Ss PARAMETERS
.Bl -tag -offset ||| -width |
.It Fl k Ar file
Use
.Ar file
as database. The default is ~/.kc/default.
.It Fl r
Open the database in read only mode.
.Nm
will not try to lock the database file, and commands which could modify the database will not be available.
.It Fl p Ar file
Read password from
.Ar file .
.It Fl m Ar mode
Cipher mode to use.
.Ar mode
can be one of 'cbc' (the default), 'cfb128' or 'ofb'. More information is in the
.Em CIPHERS
section.
.It Fl b
Batch mode. Disable some features to enable commands from standard input.
.It Fl v
Display version.
.It Fl h
Display help.
.El
.Ss COMMANDS
These commands can be used in the CLI:
.Bl -tag -offset ||| -width |
.It Cm new Op name
Create a new key in the current keychain. If
.Ar name
is specified it will be the key's name, otherwise prompt for that too.
.Pp
It is possible to enter multiline values by writing
.Ql \en
in place of a desired new line. One can escape this with
.Ql \e\en .
.Pp
The
.Ql \er ,
.Ql \eR ,
.Ql \ea
and
.Ql \eA
escape sequences can be used in values to request random characters in place of them.
.Ql \er
and
.Ql \eR
will be replaced with 2 and 4 (respectively) random printable characters.
.Ql \ea
and
.Ql \eA
will be replaced with 2 and 4 (respectively) random alpha-numeric characters. Escaping can be achieved with the same technique as with
.Ql \en
(eg.:
.Ql \e\ea
).
.Pp
Every escape sequence can be used in values regardless of its order or count.
.It Cm list Op keychain
List the keys in the current keychain or if specified, in the keychain named
.Ar keychain .
Every key gets prefixed by its index number.
.Ar keychain
can be an index number or the keychain's name.
.It Cm ls Op keychain
Alias of 'list'.
.It Cm edit Ar index
Edit a key in the current keychain.
.Ar index
is the key's index number in the current keychain.
.Pp
New line and random character escape sequence rules in values apply to this command also. See command
.Cm new
for more information about this.
.It Cm search Ar string
Search for
.Ar string
in key names in the current keychain.
If the
.Cm search
command is prefixed by a '*' (eg.: *search) then search in every keychain in the current database.
.It Cm / Ar pattern
Search for
.Ar pattern
regular expression in key names in the current keychain.
If the
.Cm /
command is prefixed by a '*' (eg.: */) then search in every keychain in the current database.
.It Cm csearch Ar string
Search for
.Ar string
in keychain names in the current database.
.It Cm c/ Ar pattern
Search for
.Ar pattern
regular expression in keychain names in the current database.
.It Cm c Ar keychain
Change the current keychain.
.Ar keychain
can be an index number or the keychain's name.
.It Cm cdel Ar keychain
Delete a keychain.
.Ar keychain
can be an index number or the keychain's name.
.It Cm clear Op count
Emulate a screen clearing. Scrolls 50 lines by default, which can be multiplied by
.Ar count
times if specified.
.It Cm clist
List keychains in the current database. Every keychain gets prefixed by its index number.
.It Cm cls
Alias of 'clist'.
.It Cm cnew Op name
Create a new keychain. If
.Ar name
is not given then prompt for one.
.It Cm copy Ar index Ar keychain
Copy a key in the current keychain to another keychain.
.Ar index
is the key's index to copy and
.Ar keychain
is the destination keychain's index number or name.
.It Cm cp Ar index Ar keychain
Alias of 'copy'.
.It Cm move Ar index Ar keychain
Move a key in the current keychain to another keychain.
.Ar index
is the key's index to move and
.Ar keychain
is the destination keychain's index number or name.
.It Cm mv Ar index Ar keychain
Alias of 'move'.
.It Cm cren Ar keychain
Rename a keychain.
.Ar keychain
can be an index number or the keychain's name.
.It Cm del Ar index
Delete a key from the current keychain.
.Ar index
is the key's index number in the current keychain.
.It Cm rm Ar index
Alias of 'del'.
.It Cm passwd
Change the current database's password. All changes will be written immediately.
.It Cm help Op command
Print application help or describe a
.Ar command .
.It Cm xport Ar filename
Export the current database as an XML file named
.Ar filename .
(see command
.Cm import )
.Em NOTE :
the created XML file will be plain text, and any existing files named
.Ar filename
will be overwritten.
.It Cm import Ar filename
Import a database from
.Ar filename .
It must be a properly formatted
.Nm
database. (see command
.Cm xport )
.Em NOTE :
The current database will be overwritten if saved.
.It Cm quit
Quit the program. If the database is modified, then ask if it should be saved.
.It Cm exit
Alias of 'quit'.
.It Cm random Op length
Print a random string with
.Ar length
length. The default
.Ar length
is 8.
.It Cm version
Display the program version.
.It Cm write
Save the current database.
.It Cm save
Alias of 'write'.
.El
.Ss CIPHERS
All ciphers use 128 bit keys, generated with a KDF (key-derivation function) from the supplied password, an IV (initialization vector) and a salt. Both the IV and the salt are 128 bits long and read from the host's specific random device (/dev/urandom on Linux and /dev/random on everything else).
.Sh CAVEATS
If you use 'cfb128' or 'ofb' for cipher, there is no specific sign if you enter a wrong password during the opening of a database; in this case the database would seem to be corrupt after decrypting, and
.Nm
will not be able to open it.
.Pp
There is no character conversion taking place for the input fields.
.Sh AUTHOR
.Nm
was written by
.An Daniel LEVAI
<leva@ecentrum.hu>
.Pp
Source, information, bugs:
http://keychain.googlecode.com
